### ISSUE TITLE
Openvario on Cubietruck (dri device error)

### ISSUE THREAD

**Issue by palomba01** [Openvario/meta-openvario#132]
I'm testing the openvario on a cubieboard3 (Cubietruck), but after the openvario background on boot it appears the following error:
"Exiting... 
Using DRI device /dev/dri/card0 (use environment variable DRI_DEVICE to override"
Any tips for fixing this error?

**Comment by hor63** [comment]
Check if /dev/dri/card1 existists. If not you do not have a working Lima driver compiled in your kernel or loaded.
Check journalctl and dmesg for "lima", if messages exist, and if there are any errors upon loading.
If it exists try:
`DRI_DEVICE=/dev/dri/card1 -xcsoar`

**Comment by linuxianer99** [comment]
Is this still a valid issue ??
Think Cubietruck is not a supported platform ....

**Comment by hor63** [comment]
Cubietruck still uses the A20. Thus this is merely a question of packaging that the actual software, particularly when the issue deals with the Mali which is independent from the board where the A20 is soldered to.

But since there is also no feedback to my answer since August there seems not to be any more interest.
